spring.application.name=expense-splitter

# Spring Boot Application Port
server.port=${PORT:8080}

# -----------------
# 1. PostgreSQL Database Configuration
# -----------------
spring.datasource.url=jdbc:postgresql://dpg-d5j02l3e5dus73fht050-a.oregon-postgres.render.com/trip_expense_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=trip_expense_db_user
spring.datasource.password=EeQBIFHGgF5pBKtZNysNzvuKeOnsLbeU

# -----------------
# 2. JPA/Hibernate Configuration (Database Table Creation)
# -----------------
# DDL-AUTO: Automatically creates/updates tables based on Java Entities
spring.jpa.hibernate.ddl-auto=create

# Shows the SQL queries in the console for debugging
spring.jpa.show-sql=true

# -----------------
# 3. JPA Dialect for PostgreSQL
# -----------------
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ---------------
# Mobile Access
#-----------------

server.address=0.0.0.0