spring.application.name=expense-splitter

# Spring Boot Application Port
server.port=${PORT:8080}

# -----------------
# 1. PostgreSQL Connection (Render)
# -----------------
spring.datasource.url=jdbc:postgresql://dpg-d4tvpfshg0os739fsrqg-a.oregon-postgres.render.com/trip_expenses_db_nt8l
spring.datasource.username=tripsplitter
spring.datasource.password=iVFDcjpvjN7tA5x46KJajSVy6dWgSUEv

# -----------------
# 2. JPA/Hibernate Configuration (Database Table Creation)
# -----------------
# DDL-AUTO: Automatically creates/updates tables based on Java Entities
spring.jpa.hibernate.ddl-auto=update

# Shows the SQL queries in the console for debugging
spring.jpa.show-sql=true