spring.application.name=expense-splitter

# Spring Boot Application Port
server.port=${PORT:8080}

# -----------------
# 1. PostgreSQL Connection (Render)
# -----------------
spring.datasource.url=<RENDER_POSTGRES_URL>
spring.datasource.username=<RENDER_POSTGRES_USER>
spring.datasource.password=<RENDER_POSTGRES_PASSWORD>

# -----------------
# 2. JPA/Hibernate Configuration (Database Table Creation)
# -----------------
# DDL-AUTO: Automatically creates/updates tables based on Java Entities
spring.jpa.hibernate.ddl-auto=update

# Shows the SQL queries in the console for debugging
spring.jpa.show-sql=true